#### Numpy Array

In [11]:
import numpy as np

n = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9))
print(n)
print(n.shape)  # Output: (9,) - 1D array with 9 elements
print(n.ndim)    # Output: 1 - 1D array

n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(n)
print(n.shape)  # Output: (3, 3) - 2D array with 3 rows and 3 columns
print(n.ndim)    # Output: 2 - 2D array

[1 2 3 4 5 6 7 8 9]
(9,)
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


#### Initialize Array

In [17]:
import numpy as np

n=np.zeros((3, 3))
print(n)

print("\n") 

n=np.ones((2, 5))
print(n)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### Numpay Array Slicing


In [ ]:
import numpy as np
n=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(n[0, 0])  # Accessing element at row 0, column 0
print(n[0, :])  # Accessing all elements in row 0
print(n[:, 0])  # Accessing all elements in column 0
print(n[0:3])  # Accessing elements from row 1 to row 2 (exclusive)


1
[1 2 3]
[1 4 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

n=np.array((1, 2, 3, 4, 5, 6, 7, 8, 9))
print(n[2:5]) # Accessing elements from index 2 to 4 (exclusive)

[3 4 5]


In [ ]:
import numpy as np

n=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(n[2:5]) 
print(n.shape) 
print(n.ndim) 

In [17]:
import numpy as np

n=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
for a in n1:
   print(a)


re_shape=n.reshape(3,3)
print("original array: ",n)
print("Re shaped array:\n",re_shape)

1
2
3
4
5
6
7
8
9
original array:  [1 2 3 4 5 6 7 8 9]
Re shaped array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Join  -concatenate, stack

In [29]:
import numpy as np

n1=np.array([1,2,3,4,5,6,7,8,9])
n2=np.array([10,11,12,13,14,15,16,17,18,19])



re_shape=np.concatenate((n1,n2))
print("After concatenate:\n",re_shape)

re_shape=np.hstack((n1,n2))  #same as concatenate
print("After hstack:\n",re_shape)

n2=np.array([11,12,13,14,15,16,17,18,19])

re_shape=np.stack((n1,n2))  #shape must be same and output in shape
print("After stack:\n",re_shape)
re_shape=np.vstack((n1,n2))  #in roww
print("After vstack:\n",re_shape)

re_shape=np.dstack((n1,n2))  #in column
print("After dstack:\n",re_shape)



After concatenate:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
After hstack:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
After stack:
 [[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]]
After vstack:
 [[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]]
After dstack:
 [[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]
  [ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]]]
